# ADD ALL PROJECT GRAPH DESCRIPTIONS TO THE BELOW DICTIONARY.
# KEY SHOULD BE SHORT/GRAPHSPECIFIC, AND VALUE SHOULD BE YOUR DESCRIPTION
descriptions = {"crime": " what is crime", "attend": "waht is suspension"}
